name: Upload Python Package

on:
  push:
    branches: [ci/release]
    # tags:
    #   - 'v*'  # Triggers on any tag that starts with 'v'

permissions:
  contents: read

jobs:
  # tests:
  #   uses: ./.github/workflows/tests.yml  # use the callable tests job to run tests
  
  deploy:
    runs-on: ubuntu-latest
    # run on tag only
    # if: startsWith(github.ref, 'refs/tags/')
    # needs: [tests]  # require tests to pass before deploy runs
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      contents: read
    environment:
      name: pypi
      url: https://pypi.org/p/mjinx 
    steps:
      - name: "Checkout Git repository"
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build --wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
