name: Documentation

on:
  push:
    branches: [ main, docs/github_pages ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: "GitHub Pages"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout Git repository"
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install ".[all]"

      - name: "Build documentation"
        run: |
          sphinx-build docs _build -W

      # TODO: uncomment when repository will go public
      # - name: "Deploy to GitHub Pages"
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/docs/github_pages' }}
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: _build/
      #     force_orphan: true